version: '3.4'

services:
  mongo:
    container_name: mongo
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
     MONGO_INITDB_ROOT_USERNAME: root
     MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - db_data:/data/db
  
  mongo-express:
   container_name: mongo-express
   image: mongo-express
   restart: unless-stopped
   ports:
    - 8081:8081
   environment:
    ME_CONFIG_MONGODB_ADMINUSERNAME: root
    ME_CONFIG_MONGODB_ADMINPASSWORD: example
    ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEAFAULT_PASS=guest

  cardealerappserver:
    image: ${DOCKER_REGISTRY-}cardealerappserver
    container_name: CarDealerAppServer
    build:
      context: .
      dockerfile: CarDealerAppServer/Dockerfile
    ports:
     - 8080:80

  redis:
    container_name: redis
    image: redis/redis-stack:7.0.6-RC4
    restart: unless-stopped
    ports:
     - 6379:6379
     - 8001:8001
    volumes:
     - cache:/data

volumes:
  cache:
   driver: local
  db_data:
   driver: local
